version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.3
  - dependency-name: cssnano
    versions:
    - 5.0.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.5
