paths:
  static: static
  uploads: static/uploads
timezone: Asia/Makassar
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
collections_config:
  pages:
    path: content
    icon: wysiwyg
  notes:
    path: content/notes
    icon: notes
    glob:
      - '!_index.md'
