DefaultContentLanguage: "en"
languageCode: "en"
title: "Don Alfons"

params:
  author: "Don Alfons"
  twitter_username: "itsdonnix"
  github_username: "itsdonnix"

permalinks:
    notes: "/notes/:slug"

taxonomies:
  tag: "tags"

build:
  writeStats: true

markup:
  highlight:
    codeefence: false
    noClasses: false

  goldmark:
    renderer:
      unsafe: true
