DefaultContentLanguage: "en"
languageCode: "en"
title: "Don Alfons"

params:
  author: "Don Alfons"
  twitter_username: "itsdonnix"
  github_username: "itsdonnix"
  GTM_ID: "GTM-KNRCKP9Fx"
  avatar_size: 150 # Default size in pixels
  profile_alt_text: "Profile Picture of Don Alfons" # Configurable alt text

permalinks:
  notes: "/notes/:slug"

taxonomies:
  tag: "tags"

build:
  writeStats: true

markup:
  highlight:
    codeefence: false
    noClasses: false

  goldmark:
    renderer:
      unsafe: true
