name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"

      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.2"

      # - name: Install PostCSS CLI
      #   run: sudo npm install -g tailwindcss postcss-cli@latest autoprefixer@latest

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: github.event_name != 'pull_request'

      - name: Install Dependencies (for PR only)
        run: pnpm install --no-frozen-lockfile
        if: github.event_name == 'pull_request'

      - name: Hugo Build
        run: hugo --baseURL https://donnisnoni.github.io --minify && pnpm run build-css

      - name: Generate Resume PDF
        run: pnpm run generate-resume-pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        if: github.event_name != 'pull_request'
